### ISSUE TITLE
Do we need "QUIT"?

### ISSUE THREAD

**Issue by sci4me** [sci4me/yakvs#1]
If a client closes the connection, the connection will be closed automatically. Therefore, it seems redundant to have QUIT.

To be quite honest, I added it for convenience while testing yakvs with telnet.

Should it be removed?

**Comment by rameshg87** [comment]
I think we should just keep this since it was added. If someone had started using this, then it would simple break their changes as QUIT will result in "Invalid command".

**Comment by sci4me** [comment]
Yeah at this point, I agree.
